services:
  - type: web
    name: Music Player
    env: static
    buildCommand: ./build-whole.sh
    staticPublishPath: music-player-web/build
    pullRequestPreviewsEnabled: false
    buildFilter:
      paths:
        - src/**/*.tsx
      ignoredPaths:
        - src/**/*.test.ts
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
    envVars:
      - key: YARN_ENABLE_IMMUTABLE_INSTALLS
        value: false
    autoDeploy: true
